export declare const Get: (path: string) => (target: any, propertyKey: string) => void;
export declare const Post: (path: string) => (target: any, propertyKey: string) => void;
export declare const Patch: (path: string) => (target: any, propertyKey: string) => void;
export declare const Put: (path: string) => (target: any, propertyKey: string) => void;
export declare const Delete: (path: string) => (target: any, propertyKey: string) => void;
export declare const BodyCorps: () => (target: any, propertyKey: string | symbol) => any;
export declare const Res: () => (target: any, propertyKey: string | symbol) => any;
export declare const Req: () => (target: any, propertyKey: string | symbol) => any;
export declare const Params: (params: string) => (target: any, propertyKey: string | symbol, parameterIndex: number) => any;
export declare const Cookies: (cookies: string) => (target: any, propertyKey: string | symbol) => any;
export declare const UserReq: () => (target: any, propertyKey: string | symbol) => any;
export declare const Headers: (headers: string) => (target: any, propertyKey: string | symbol) => any;
export declare const Next: () => (target: any, propertyKey: string | symbol) => any;
