"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseEntity = exports.BodyCorps = exports.Put = exports.Delete = exports.Post = exports.Patch = exports.Get = exports.Controller = exports.configureRoutes = void 0;
const controller_1 = require("./controller");
Object.defineProperty(exports, "configureRoutes", { enumerable: true, get: function () { return controller_1.configureRoutes; } });
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_1.Controller; } });
const decorator_1 = require("./decorator");
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return decorator_1.Get; } });
Object.defineProperty(exports, "Patch", { enumerable: true, get: function () { return decorator_1.Patch; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return decorator_1.Post; } });
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return decorator_1.Delete; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return decorator_1.Put; } });
Object.defineProperty(exports, "BodyCorps", { enumerable: true, get: function () { return decorator_1.BodyCorps; } });
const base_entity_1 = require("./Entity/base-entity");
Object.defineProperty(exports, "BaseEntity", { enumerable: true, get: function () { return base_entity_1.BaseEntity; } });
